article/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleCreateView

app_name = "article"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", ArticleUpdateView.as_view(), name="edit"),
]

info/urls.py
from django.urls import path
from .views import (
    VacancyListView,
    VacancyDetailView,
    VacancyCreateView,
    VacancyUpdateView,
    PageDetailView,
    PageUpdateView,
)

app_name = "info"

urlpatterns = [
    # Вакансии
    path("vacancies/", VacancyListView.as_view(), name="vacancy_list"),
    path("vacancies/create/", VacancyCreateView.as_view(), name="vacancy_create"),
    path("vacancies/<int:pk>/", VacancyDetailView.as_view(), name="vacancy_detail"),
    path("vacancies/<int:pk>/edit/", VacancyUpdateView.as_view(), name="vacancy_edit"),

    # Универсальные страницы
    path("page/<str:page_type>/", PageDetailView.as_view(), name="page"),
    path("page/<int:pk>/edit/", PageUpdateView.as_view(), name="page_edit"),

]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import HomeView, HomeBlockCreateView, HomeBlockUpdateView

app_name = "main"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("blocks/create/", HomeBlockCreateView.as_view(), name="block_create"),
    path("blocks/<int:pk>/edit/", HomeBlockUpdateView.as_view(), name="block_edit"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout")
]

project/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectUpdateView, ProjectCreateView

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="list"),
    path("create/", ProjectCreateView.as_view(), name="create"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", ProjectUpdateView.as_view(), name="edit"),
]

request/urls.py
from django.urls import path
from .views import RequestCreateView

app_name = "request"

urlpatterns = [
    path("", RequestCreateView.as_view(), name="form"),
]

templates/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>

<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- SEO -->
        <title>
            {% if seo_title %}
                {{ seo_title }}
            {% elif page_title %}
                {{ page_title }}
            {% else %}
                {% block title %}Guidejet TI{% endblock %}
            {% endif %}
        </title>

        <meta name="description"
            content="{% if seo_description %}{{ seo_description }}{% else %}Guidejet TI – цифровые решения и информационные системы для города{% endif %}">

        <meta name="keywords"
            content="{% if seo_keywords %}{{ seo_keywords }}{% else %}Guidejet TI, IT, цифровые решения, Алматы{% endif %}">

        <!-- OpenGraph для соцсетей -->
        <meta property="og:title"
            content="{% if seo_title %}{{ seo_title }}{% elif page_title %}{{ page_title }}{% else %}Guidejet TI{% endif %}">
        <meta property="og:description"
            content="{% if seo_description %}{{ seo_description }}{% else %}Guidejet TI – цифровые решения и информационные системы для города{% endif %}">

        <!-- Tailwind + daisyUI -->
        <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <script src="https://unpkg.com/heroicons@2.1.1/dist/heroicons.min.js"></script>

        {% block css %}{% endblock %}
        <link rel="icon" href="{% static 'favicon/favicon.ico' %}">
    </head>
    <body>
        <!-- ================= NAVBAR ================= -->
        <div class="navbar bg-base-100 shadow-sm relative z-50">
            <div class="navbar-start">
                <div class="dropdown">
                    <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
                    </div>
                    <ul
                        tabindex="-1"
                        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
                        <li><a href="{% url 'main:home' %}">Главная</a></li>
                        <li><a href="{% url 'project:list' %}">Проекты</a></li>
                        <li><a href="{% url 'article:list' %}">Новости</a></li>
                        <li><a href="{% url 'info:page' 'about' %}">О компании</a></li>
                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'main:logout' %}">
                        {% csrf_token %}
                        <button type="submit"
                            class="m-3 btn btn-outline btn-xs gap-2 lg:hidden">

                            <!-- Иконка выхода -->
                            <svg xmlns="http://www.w3.org/2000/svg"
                                class="h-4 w-4"
                                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a2 2 0 01-2 2H5a2 2 0 01-2-2V6a2 2 0 012-2h6a2 2 0 012 2v1"/>
                            </svg>
                        </button>
                    </form>
                {% else %}
                    <!-- Войти -->
                    <a href="{% url 'main:login' %}"
                    class="m-3 btn btn-outline btn-xs gap-2 lg:hidden">
                        <!-- Иконка входа -->
                        <svg xmlns="http://www.w3.org/2000/svg"
                            class="h-4 w-4"
                            fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4M10 17l5-5m0 0l-5-5m5 5H3"/>
                        </svg>
                    </a>
                {% endif %}

                <a href="{% url 'main:home' %}" class="btn btn-ghost text-xl mx-5 flex items-center gap-2">
                    <img class="ui centered image" src="{% static 'logo/mini.png' %}" width="35">
                    <span class="text-xs md:text-xl">Guidejet TI</span>
                </a>

            </div>
            <div class="navbar-center hidden lg:flex">
                <ul class="menu menu-horizontal px-1">
                    <li><a href="{% url 'main:home' %}">Главная</a></li>
                    <li><a href="{% url 'project:list' %}">Проекты</a></li>
                    <li><a href="{% url 'article:list' %}">Новости</a></li>
                    <li><a href="{% url 'info:page' 'about' %}">О компании</a></li>
                </ul>
            </div>
            <div class="navbar-end">

                <div class="flex items-center">

                    <!-- Связаться с нами -->
                    <a href="{% url 'request:form' %}"
                    class="lg:hidden m-3 btn btn-primary btn-outline gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            class="w-5 h-5">
                        <path d="M3.105 2.289a.75.75 0 01.81-.07l13.5 6.75a.75.75 0 010 1.342l-13.5 6.75a.75.75 0 01-1.065-.81l1.68-5.881L9 10 4.53 9.63l-1.68-5.88a.75.75 0 01.255-.761z"/>
                        </svg>
                    </a>

                    <a href="{% url 'request:form' %}"
                    class="hidden lg:flex m-3 btn btn-outline btn-primary btn-base gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            class="w-5 h-5">
                        <path d="M3.105 2.289a.75.75 0 01.81-.07l13.5 6.75a.75.75 0 010 1.342l-13.5 6.75a.75.75 0 01-1.065-.81l1.68-5.881L9 10 4.53 9.63l-1.68-5.88a.75.75 0 01.255-.761z"/>
                        </svg>
                        Связаться с нами
                    </a>

                    {% if user.is_authenticated %}
                        <form method="post" action="{% url 'main:logout' %}" class="inline">
                            {% csrf_token %}
                            <button type="submit"
                                class="hidden lg:flex m-3 btn btn-outline btn-base gap-2">

                                <!-- Иконка выхода -->
                                <svg xmlns="http://www.w3.org/2000/svg"
                                    class="h-4 w-4"
                                    fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a2 2 0 01-2 2H5a2 2 0 01-2-2V6a2 2 0 012-2h6a2 2 0 012 2v1"/>
                                </svg>
                            </button>
                        </form>
                    {% else %}
                        <!-- Войти -->
                        <a href="{% url 'main:login' %}"
                        class="hidden lg:flex m-3 btn btn-outline btn-base gap-2">
                            <!-- Иконка входа -->
                            <svg xmlns="http://www.w3.org/2000/svg"
                                class="h-4 w-4"
                                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4M10 17l5-5m0 0l-5-5m5 5H3"/>
                            </svg>
                        </a>
                    {% endif %}
                </div>

            </div>
        </div>
        <!-- ================= CONTENT ================= -->
        <div style="min-height: calc(100vh - 220px);">
            {% block content %}{% endblock %}
        </div>
        <!-- ================= FOOTER ================= -->
        {% block footer %}
            <footer class="footer sm:footer-horizontal bg-black text-neutral-content p-10">
                <aside>
                    <img class="mb-5" src="{% static 'logo/full_white.png' %}" width="200">
                    <p class="font-bold">
                    ТОО «Guidejet TI» (Гайджет ТиАй)
                    </p>
                    <p>&copy; {% now "Y" %}</p>
                    <p class="text-xs">
                        Юридический адрес:<br>
                        Республика Казахстан, <br>
                        г. Алматы, Ауэзовский район, <br>
                        микрорайон Астана 7/1 <br>
                    </p>
                </aside>
                <nav>
                    <h6 class="footer-title">Полезная информация</h6>
                    <a href="{% url 'info:page' 'about' %}" class="link link-hover">О компании</a>
                    <a href="{% url 'info:page' 'cooperation' %}" class="link link-hover">Сотрудничество</a>
                    <a href="{% url 'info:vacancy_list' %}" class="link link-hover">Вакансии</a>
                    <a href="{% url 'info:page' 'faq' %}" class="link link-hover">F.A.Q.</a>
                </nav>
                <nav>
                    <h6 class="footer-title">Навигация по сайту</h6>
                    <a href="{% url 'main:home' %}" class="link link-hover">Главная</a>
                    <a href="{% url 'project:list' %}" class="link link-hover">Проекты</a>
                    <a href="{% url 'article:list' %}" class="link link-hover">Новости</a>
                    {% if user.is_authenticated %}
                        <form method="post" action="{% url 'main:logout' %}" class="inline">
                            {% csrf_token %}
                            <button type="submit" class="link link-hover">
                                Выйти
                            </button>
                        </form>
                    {% else %}
                        <!-- Войти -->
                        <a href="{% url 'main:login' %}" class="link link-hover">
                            Войти
                        </a>
                    {% endif %}
                </nav>
                <nav>
                    <h6 class="footer-title">Обратная связь</h6>
                    <a href="{% url 'request:form' %}" class="link link-hover">Отправить сообщение на сайте</a>
                    <a href="mailto:topo@guidejet.kz" class="link link-hover">topo@guidejet.kz</a>
                </nav>
                <p class="text-xs">
                    <img class="ui centered image" src="{% static 'astana_hub.svg' %}" width="130">
                    Участник международного
                    <br>
                    технологического парка "Астана Хаб"
                </p>
            </footer>
        {% endblock %}
        {% block js %}{% endblock %}
    </body>
</html>